### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by dorrzun** [portobello-boy/Advent2023#1]
I'm having issues pulling down and running this code.
The current issue I'm getting is Golang. That's right folks, Golang is the problem.

<3 Beeg Schluv <3

**Comment by portobello-boy** [comment]
> I'm having issues pulling down and running this code. The current issue I'm getting is Golang. That's right folks, Golang is the problem.
> 
> <3 Beeg Schluv <3

If you're having issues installing Golang, then I think the problem is between the chair and the keyboard. I heard that's a tough problem to solve, but I have faith you can find the cause ;)

Beeg Schluv
